version: "2"

linters:
  default: standard
  enable:
    - staticcheck
    - errcheck
    - gosec
    - govet
    - revive
    - unused
    - ineffassign
    - unconvert
    - prealloc
    - wastedassign
    - errorlint
    - nilerr
    - forcetypeassert
    - unparam
    - misspell
    - godot
    - bodyclose
    - sqlclosecheck
    - noctx

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: false
      - name: cyclomatic
        arguments: [15]

  staticcheck:
    checks: ["all"]

  errcheck:
    check-type-assertions: true
    check-blank: true

  gosec:
    excludes:
      - G401  # MD5 (если реально нужна)
      - G501  # DSA (если реально нужна)

issues:
  exclude-generated: lax
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    - path: _test\.go
      text: "weak random"
      linters:
        - gosec

    - text: "should not use ALL_CAPS"
      linters:
        - revive

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
